FROM tensorflow/tensorflow:2.9.0-gpu


# Install the required packages
RUN pip install keras_cv==0.3.4 \
    matplotlib==3.5.2 \
    numpy==1.23.1 \
    Pillow==9.3.0 \
    scipy==1.9.1 \
    tensorflow_datasets \
    fastapi \
    uvicorn \
    python-multipart


